# Generated by Django 6.0.5 on 2026-05-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('imap_server', models.CharField(max_length=250)),
            ],
        ),
    ]
