# Generated by Django 6.0.5 on 2026-05-19 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('message_id', models.TextField(blank=True, null=True)),
                ('sender', models.TextField(blank=True, null=True)),
                ('recipient', models.TextField(blank=True, null=True)),
                ('cc', models.TextField(blank=True, null=True)),
                ('bcc', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_to', models.TextField(blank=True, null=True)),
                ('return_path', models.TextField(blank=True, null=True)),
                ('x_mailer', models.TextField(blank=True, null=True)),
                ('received_spf', models.TextField(blank=True, null=True)),
                ('dkim_signature', models.TextField(blank=True, null=True)),
                ('dmarc', models.TextField(blank=True, null=True)),
                ('received_chain', models.JSONField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('raw_email', models.BinaryField(blank=True, null=True)),
                ('source_folder', models.CharField(default='INBOX', max_length=255)),
                ('is_multipart', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('content', models.BinaryField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Mailbox.emailrecord')),
            ],
        ),
    ]
