# Generated by Django 6.0.5 on 2026-05-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='app_password',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
