# Generated by Django 6.0.5 on 2026-06-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailbox', '0003_emailrecord_emailattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
