# Generated by Django 6.0.5 on 2026-06-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailbox', '0004_emailrecord_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
    ]
