# Generated by Django 6.0.5 on 2026-06-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mailbox', '0003_emailrecord_emailattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_type', models.CharField(choices=[('url', 'URL'), ('ip', 'IP Address'), ('domain', 'Domain'), ('email', 'Email Address')], max_length=10)),
                ('value', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('is_malicious', models.BooleanField(blank=True, default=None, null=True)),
                ('threat_score', models.IntegerField(blank=True, default=None, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('email_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iocs', to='Mailbox.emailrecord')),
            ],
            options={
                'ordering': ['-detected_at'],
                'unique_together': {('email_record', 'ioc_type', 'value')},
            },
        ),
    ]
