# Generated by Django 6.0.5 on 2026-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioc',
            name='ioc_type',
            field=models.CharField(choices=[('url', 'URL'), ('ip', 'IP Address'), ('domain', 'Domain'), ('email', 'Email Address'), ('hash', 'File Hash')], max_length=10),
        ),
    ]
