# Generated by Django 6.0.5 on 2026-06-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_ioc_ioc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='file_hash',
            field=models.CharField(blank=True, null=True),
        ),
    ]
