# Generated by Django 6.0.5 on 2026-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_ioc_file_hash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ioc',
            unique_together={('ioc_type', 'value')},
        ),
        migrations.AddField(
            model_name='ioc',
            name='email_ids',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ioc',
            name='email_record',
        ),
    ]
