# Generated by Django 6.0.5 on 2026-07-04 07:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailbox', '0005_emailrecord_scanned'),
        ('analyzer', '0004_alter_ioc_unique_together_ioc_email_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('verdict', models.CharField(choices=[('Safe', 'Safe'), ('Suspicious', 'Suspicious'), ('Malicious', 'Malicious')], default='Safe', max_length=20)),
                ('classification', models.CharField(choices=[('Clean', 'Clean'), ('Spam', 'Spam'), ('Phishing', 'Phishing')], default='Clean', max_length=20)),
                ('phising_type', models.CharField(max_length=50, null=True)),
                ('ioc_risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ml_risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('authentication_risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('analyst_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mailbox.emailrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
