# Generated by Django 6.0.5 on 2026-07-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_analysisreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
