# Generated by Django 6.0.5 on 2026-07-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_ioc_is_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
