# Generated by Django 6.0.5 on 2026-07-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
