# Generated by Django 6.0.5 on 2026-07-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_delete_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abuseipdb_key', models.CharField(blank=True, max_length=255, null=True)),
                ('virustotal_key', models.CharField(blank=True, max_length=255, null=True)),
                ('malwarebazaar_key', models.CharField(blank=True, max_length=255, null=True)),
                ('google_safe_browsing_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
