# Generated by Django 6.0.5 on 2026-07-13 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_apikeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
